routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    $helloworld = "Hello World!";
    return view('welcome', compact('helloworld'));
})->name('home');

Route::get('/model', function (){

    // $products = \App\Product::all(); //SELECT * FROM Products

    //    $user = \App\User::find(1);
    //    $user = new \App\User();
    //    $user->name = 'Usuario Teste';
    //    $user->email = 'email@teste.com';
    //    $user->password = bcrypt('12345678');
    //    $user->save();

    //    return \App\User::all();

    //    Mass Assigment - Atribuição em Massa

    //    $user = \App\User::create([
    //        'name' => 'Rebeka Odilon',
    //        'email' => 'rebeka@email.com',
    //        'password' => bcrypt('2134567890')
    //    ]);
    //    dd($user);

    //    Mass Update - Atualização em Massa
    //    $user = \App\User::find(4);
    //    $user->update([
    //        'name' => 'Atualizando com mass update...'
    //    ]); // Retorna true ou false
    //    dd($user);


    /**
     * Como eu faria para pegar a loja de um usuário
     */
    // $user = \App\User::find(6);

    // dd($user->store()->count()); //Objeto único (Store) se for Collection de Dados(Objetos)


    /**
     * Como fazer para pegar os produtos de uma loja?
     */
    // $loja = \App\Store::find(1);

    // return $loja->product;

    /**
     * Como pegar as categorias de uma loja?
     */
    // $categoria = \App\Category::find(1);

    // $categoria->product;


    /**
     * Criar uma loja para um usuário
     */
    // $user = \App\User::find(10);

    // $loja = $user->store()->create([
    //     'name' => 'Loja Teste',
    //     'description' => 'Loja teste de produtos de informática',
    //     'phone' => 'XXXXX-XXXX',
    //     'mobile_phone' => 'XXXXX-XXXX',
    //     'slug' => 'loja-teste'
    // ]);

    /**
     * Criar um produto para uma loja
     */
    // $loja = \App\Store::find(7);

    // $produto = $loja->product()->create([
    //     'name' => 'Notebook Dell',
    //     'description' => 'CORE i9 16GB',
    //     'body' => 'Lorem ipsum dolor sit amet',
    //     'price' => 5999.90,
    //     'slug' => 'notebook-dell',
    // ]);

    /**
     * Criar uma categoria
     */
    // \App\Category::create([
    //     'name' => 'Games',
    //     'description' => null,
    //     'slug' => 'games'
    // ]);

    // \App\Category::create([
    //     'name' => 'Notebooks',
    //     'description' => null,
    //     'slug' => 'notebooks'
    // ]);

    // return \App\Category::all();

    /**
     * Adicionar uma categoria para um produto e vice-versa
     */
    // $produto = \App\Product::find(6);

    // dd($produto->categories()->sync([1, 2]));

    $product = \App\Product::find(6);

    return $product;
});

Route::group(['middleware' => ['auth']], function(){
    Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function(){

        //    Route::prefix('stores')->name('stores.')->group(function(){
        
            //         Route::get('/', 'StoreController@index')->name('index');
        
            //         Route::get('/create', 'StoreController@create')->name('create');
        
            //         Route::post('/store', 'StoreController@store')->name('store');
        
            //         Route::get('/{store}/edit', 'StoreController@edit')->name('edit');
        
            //         Route::post('/update/{store}', 'StoreController@update')->name('update');
        
            //         Route::get('/destroy/{store}', 'StoreController@destroy')->name('destroy');
        
        //    });
        
           Route::resource('stores', 'StoreController');
           Route::resource('products', 'ProductController');
        
        });
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');//->middleware('auth');

app/Store.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    protected $fillable = [
        'name',
        'description',
        'phone',
        'mobile_phone',
        'slug'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function product()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/StoreController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\StoreRequest;

class StoreController extends Controller
{
    public function index()
    {
        $stores = auth()->user()->store;
        return view('admin.stores.index', compact('stores'));
    }

    public function create()
    {
        if (auth()->user()->store()->count()) {
            return redirect()->route();
        }
        $users = \App\User::all(['id', 'name']);

        return view('admin.stores.create', compact('users'));
    }

    public function store(StoreRequest $request)
    {
        $data = $request->all();

        $user = auth()->user();

        $store = $user->store()->create($data);

        flash('Loja Criada com Sucesso!')->success();
        return redirect()->route('admin.stores.index');
    }

    public function edit($store)
    {
        $store = \App\Store::find($store);

        return view('admin.stores.edit', compact('store'));
    }

    public function update(StoreRequest $request, $store)
    {
        $data = $request->all();

        $store = \App\Store::find($store);
        $store->update($data);

        flash('Loja Atualizada com Sucesso!')->success();
        return redirect()->route('admin.stores.index');
    }

    public function destroy($store)
    {
        $store = \App\Store::find($store);
        $store->delete();

        flash('Loja Removida com Sucesso!')->success();
        return redirect()->route('admin.stores.index');
    }
}

resources/views/admin/stores/create.blade.php
@extends('layouts.app')

@section('content')

    <h1>Criar Loja</h1>
    <form action="{{ route('admin.stores.store') }}" method="POST">

        @csrf

        <div class="form-group">
            <label>Nome Loja</label>
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}">
            
            @error('name')
            <div class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control @error('description') is-invalid @enderror" value="{{ old('description') }}">
            
            @error('description')
            <div class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </div>
            @enderror
        </div>


        <div>
            <label>Telefone</label>
            <input type="text" name="phone" class="form-control @error('phone') is-invalid @enderror" value="{{ old('phone') }}">
            
            @error('phone')
            <div class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </div>
            @enderror
        </div>


        <div class="form-group">
            <label>Celular/Whatsapp</label>
            <input type="text" name="mobile_phone" class="form-control @error('mobile_phone') is-invalid @enderror" value="{{ old('mobile_phone') }}">
            
            @error('mobile_phone')
            <div class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </div>
            @enderror
        </div>


        <div class="form-group">
            <label>Slug</label>
            <input type="text" name="slug" class="form-control">
        </div>


        <div>
            <button class="btn btn-lg btn-success" type="submit">Criar Loja</button>
        </div>

    </form>
@endsection

resources/views/admin/stores/edit.blade.php
@extends('layouts.app')

@section('content')

    <h1>Atualizar Loja</h1>
    <form action="{{ route('admin.stores.update', ['store' => $store->id]) }}" method="POST">
        @method("PUT")
        @csrf
        <div class="form-group">
            <label>Nome Loja</label>
            <input type="text" name="name" class="form-control" value="{{ $store->name }}">
        </div>

        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control" value="{{ $store->description }}">
        </div>

        <div>
            <label>Telefone</label>
            <input type="text" name="phone" class="form-control" value="{{ $store->phone }}">
        </div>

        <div class="form-group">
            <label>Celular</label>
            <input type="text" name="mobile_phone" class="form-control" value="{{ $store->mobile_phone }}">
        </div>

        <div class="form-group">
            <label>Slug</label>
            <input type="text" name="slug" class="form-control" value="{{ $store->slug }}">
        </div>


        <div>
            <button class="btn btn-lg btn-success" type="submit">Atualizar Loja</button>
        </div>
    </form>
@endsection

resources/views/admin/stores/index.blade.php
@extends('layouts.app')

@section('content')

    @if(!$stores)
        <a href="{{ route('admin.stores.create') }}" class="btn btn-lg btn-success">CRIAR LOJA</a>
    @endif
    <table class="table table-triped">
        <thead>
            <tr>
                <th>#</th>
                <th>Loja</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th>{{ $stores->id }}</th>
                <th>{{ $stores->name }}</th>
                <th>
                    <a href="{{ route('admin.stores.edit', ['store' => $stores->id]) }}" class="btn btn-sm btn-primary">EDITAR</a>

                    <div class="btn-group">

                        <form action="{{ route('admin.stores.destroy', ['store' => $stores->id]) }}" method="POST">
                            @csrf
                            @method("DELETE")
                            <button type="submit" class="btn btn-sm btn-danger">REMOVER</button>
                        </form>

                    </div>
                </th>
            </tr>
        </tbody>
    </table>


@endsection