routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    $helloworld = "Hello World!";
    return view('welcome', compact('helloworld'));
})->name('home');

Route::get('/model', function (){

    // $products = \App\Product::all(); //SELECT * FROM Products

    //    $user = \App\User::find(1);
    //    $user = new \App\User();
    //    $user->name = 'Usuario Teste';
    //    $user->email = 'email@teste.com';
    //    $user->password = bcrypt('12345678');
    //    $user->save();

    //    return \App\User::all();

    //    Mass Assigment - Atribuição em Massa

    //    $user = \App\User::create([
    //        'name' => 'Rebeka Odilon',
    //        'email' => 'rebeka@email.com',
    //        'password' => bcrypt('2134567890')
    //    ]);
    //    dd($user);

    //    Mass Update - Atualização em Massa
    //    $user = \App\User::find(4);
    //    $user->update([
    //        'name' => 'Atualizando com mass update...'
    //    ]); // Retorna true ou false
    //    dd($user);


    /**
     * Como eu faria para pegar a loja de um usuário
     */
    // $user = \App\User::find(6);

    // dd($user->store()->count()); //Objeto único (Store) se for Collection de Dados(Objetos)


    /**
     * Como fazer para pegar os produtos de uma loja?
     */
    // $loja = \App\Store::find(1);

    // return $loja->product;

    /**
     * Como pegar as categorias de uma loja?
     */
    // $categoria = \App\Category::find(1);

    // $categoria->product;


    /**
     * Criar uma loja para um usuário
     */
    // $user = \App\User::find(10);

    // $loja = $user->store()->create([
    //     'name' => 'Loja Teste',
    //     'description' => 'Loja teste de produtos de informática',
    //     'phone' => 'XXXXX-XXXX',
    //     'mobile_phone' => 'XXXXX-XXXX',
    //     'slug' => 'loja-teste'
    // ]);

    /**
     * Criar um produto para uma loja
     */
    // $loja = \App\Store::find(7);

    // $produto = $loja->product()->create([
    //     'name' => 'Notebook Dell',
    //     'description' => 'CORE i9 16GB',
    //     'body' => 'Lorem ipsum dolor sit amet',
    //     'price' => 5999.90,
    //     'slug' => 'notebook-dell',
    // ]);

    /**
     * Criar uma categoria
     */
    // \App\Category::create([
    //     'name' => 'Games',
    //     'description' => null,
    //     'slug' => 'games'
    // ]);

    // \App\Category::create([
    //     'name' => 'Notebooks',
    //     'description' => null,
    //     'slug' => 'notebooks'
    // ]);

    // return \App\Category::all();

    /**
     * Adicionar uma categoria para um produto e vice-versa
     */
    // $produto = \App\Product::find(6);

    // dd($produto->categories()->sync([1, 2]));

    $product = \App\Product::find(6);

    return $product;
});

Route::group(['middleware' => ['auth']], function(){
    Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function(){

        //    Route::prefix('stores')->name('stores.')->group(function(){
        
            //         Route::get('/', 'StoreController@index')->name('index');
        
            //         Route::get('/create', 'StoreController@create')->name('create');
        
            //         Route::post('/store', 'StoreController@store')->name('store');
        
            //         Route::get('/{store}/edit', 'StoreController@edit')->name('edit');
        
            //         Route::post('/update/{store}', 'StoreController@update')->name('update');
        
            //         Route::get('/destroy/{store}', 'StoreController@destroy')->name('destroy');
        
        //    });
        
           Route::resource('stores', 'StoreController');
           Route::resource('products', 'ProductController');
        
        });
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');//->middleware('auth');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'description',
        'body',
        'price',
        'slug'
    ];

    public function store()
    {
        return $this->belongsTo(Store::class);
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Product;
use App\Http\Requests\ProductRequest;

class ProductController extends Controller
{

    private $product;

    public function __construct(Product $product)
    {
        $this->product = $product;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $products = $this->product->paginate(10);

        return view('admin.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $stores = \App\Store::all('id', 'name');

        return view('admin.products.create', compact('stores'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $data = $request->all();

        $store = \App\Store::find($data['store']);
        $store->product()->create($data);

        flash('Produto Criado com Sucesso!')->success();

        return redirect()->route('admin.products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($product)
    {
        $product = $this->product->findOrFail($product);

        return view('admin.products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, $product)
    {
        $data = $request->all();

        $product = $this->product->find($product);
        $product->update($data);

        flash('Produto Atualizado com Sucesso!')->success();

        return redirect()->route('admin.products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($product)
    {
        $product = $this->product->find($product);
        $product->delete();

        flash('Produto Removido com Sucesso!')->success();
        return redirect()->route('admin.products.index');
    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.app')


@section('content')
    <h1>Criar Produto</h1>
    <form action="{{route('admin.products.store')}}" method="post">
        @csrf

        <div class="form-group">
            <label>Nome Produto</label>
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{old('name')}}">

            @error('name')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control @error('description') is-invalid @enderror" value="{{old('description')}}">

            @error('description')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Conteúdo</label>
            <textarea name="body" id="" cols="30" rows="10" class="form-control @error('body') is-invalid @enderror">{{old('body')}}</textarea>

            @error('body')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>


        <div class="form-group">
            <label>Preço</label>
            <input type="text" name="price" class="form-control @error('price') is-invalid @enderror" value="{{old('price')}}">

            @error('price')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Slug</label>
            <input type="text" name="slug" class="form-control">
        </div>

        <div>
            <button type="submit" class="btn btn-lg btn-success">Criar Produto</button>
        </div>
    </form>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.app')


@section('content')
    <h1>Atualizar Produto</h1>

    <form action="{{route('admin.products.update', ['product' => $product->id])}}" method="post">
        @csrf
        @method("PUT")

        <div class="form-group">
            <label>Nome Produto</label>
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{$product->name}}">

            @error('name')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="description" class="form-control @error('description') is-invalid @enderror" value="{{$product->description}}">

            @error('description')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Conteúdo</label>
            <textarea name="body" id="" cols="30" rows="10" class="form-control @error('body') is-invalid @enderror">{{$product->body}}</textarea>

            @error('body')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>


        <div class="form-group">
            <label>Preço</label>
            <input type="text" name="price" class="form-control @error('price') is-invalid @enderror" value="{{$product->price}}">

            @error('price')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Slug</label>
            <input type="text" name="slug" class="form-control" value="{{$product->slug}}">
        </div>

        <div>
            <button type="submit" class="btn btn-lg btn-success">Atualizar Produto</button>
        </div>
    </form>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('content')

    <a href="{{ route('admin.products.create') }}" class="btn btn-lg btn-success">CRIAR PRODUTO</a>
    <table class="table table-triped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome</th>
                <th>Preço</th>
                <th>Loja</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($products as $p)
                <tr>
                    <th>{{ $p->id }}</th>
                    <th>{{ $p->name }}</th>
                    <th>R$ {{ number_format($p->price, 2, ',', '.') }}</th>
                    <th>{{ $p->store->name }}</th>
                    <th>
                        <a href="{{ route('admin.products.edit', ['product' => $p->id]) }}" class="btn btn-sm btn-primary">EDITAR</a>

                        <div class="btn-group">

                            <form action="{{ route('admin.products.destroy', ['product' => $p->id]) }}" method="POST">
                                @csrf
                                @method("DELETE")
                                <button type="submit" class="btn btn-sm btn-danger">REMOVER</button>
                            </form>

                        </div>
                    </th>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{ $products->links() }}

@endsection